package me.huidoudour.file.manager.ui.theme

import androidx.compose.ui.graphics.Color

// =============================================================================
//  MD3 色板 — 蓝色种子色 (#1E88E5) 生成的完整色调
// =============================================================================

// ---- Light ----
val md_light_primary = Color(0xFF0061A4)
val md_light_onPrimary = Color(0xFFFFFFFF)
val md_light_primaryContainer = Color(0xFFD1E4FF)
val md_light_onPrimaryContainer = Color(0xFF001D36)
val md_light_secondary = Color(0xFF535F70)
val md_light_onSecondary = Color(0xFFFFFFFF)
val md_light_secondaryContainer = Color(0xFFD7E3F7)
val md_light_onSecondaryContainer = Color(0xFF101C2B)
val md_light_tertiary = Color(0xFF6B5778)
val md_light_onTertiary = Color(0xFFFFFFFF)
val md_light_tertiaryContainer = Color(0xFFF2DAFF)
val md_light_onTertiaryContainer = Color(0xFF251431)
val md_light_error = Color(0xFFBA1A1A)
val md_light_onError = Color(0xFFFFFFFF)
val md_light_errorContainer = Color(0xFFFFDAD6)
val md_light_onErrorContainer = Color(0xFF410002)
val md_light_background = Color(0xFFF8F9FF)
val md_light_onBackground = Color(0xFF191C20)
val md_light_surface = Color(0xFFF8F9FF)
val md_light_onSurface = Color(0xFF191C20)
val md_light_surfaceVariant = Color(0xFFDFE2EB)
val md_light_onSurfaceVariant = Color(0xFF43474E)
val md_light_outline = Color(0xFF73777F)
val md_light_outlineVariant = Color(0xFFC3C7CF)
val md_light_surfaceDim = Color(0xFFD8DAE0)
val md_light_surfaceBright = Color(0xFFF8F9FF)
val md_light_surfaceContainerLowest = Color(0xFFFFFFFF)
val md_light_surfaceContainerLow = Color(0xFFF2F3FA)
val md_light_surfaceContainer = Color(0xFFECEEF4)
val md_light_surfaceContainerHigh = Color(0xFFE6E8EE)
val md_light_surfaceContainerHighest = Color(0xFFE1E2E8)

// ---- Dark ----
val md_dark_primary = Color(0xFF9ECAFF)
val md_dark_onPrimary = Color(0xFF003258)
val md_dark_primaryContainer = Color(0xFF00497D)
val md_dark_onPrimaryContainer = Color(0xFFD1E4FF)
val md_dark_secondary = Color(0xFFBBC7DB)
val md_dark_onSecondary = Color(0xFF253140)
val md_dark_secondaryContainer = Color(0xFF3B4858)
val md_dark_onSecondaryContainer = Color(0xFFD7E3F7)
val md_dark_tertiary = Color(0xFFD6BEE4)
val md_dark_onTertiary = Color(0xFF3B2948)
val md_dark_tertiaryContainer = Color(0xFF523F5F)
val md_dark_onTertiaryContainer = Color(0xFFF2DAFF)
val md_dark_error = Color(0xFFFFB4AB)
val md_dark_onError = Color(0xFF690005)
val md_dark_errorContainer = Color(0xFF93000A)
val md_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_dark_background = Color(0xFF111418)
val md_dark_onBackground = Color(0xFFE1E2E8)
val md_dark_surface = Color(0xFF111418)
val md_dark_onSurface = Color(0xFFE1E2E8)
val md_dark_surfaceVariant = Color(0xFF43474E)
val md_dark_onSurfaceVariant = Color(0xFFC3C7CF)
val md_dark_outline = Color(0xFF8D9199)
val md_dark_outlineVariant = Color(0xFF43474E)
val md_dark_surfaceDim = Color(0xFF111418)
val md_dark_surfaceBright = Color(0xFF37393E)
val md_dark_surfaceContainerLowest = Color(0xFF0C0E12)
val md_dark_surfaceContainerLow = Color(0xFF191C20)
val md_dark_surfaceContainer = Color(0xFF1D2024)
val md_dark_surfaceContainerHigh = Color(0xFF282A2F)
val md_dark_surfaceContainerHighest = Color(0xFF33353A)

// ---- 文件分类图标色 (亮暗主题通用, 配 12% 透明度容器背景) ----
val FileTintFolder = Color(0xFFF9A825)
val FileTintImage = Color(0xFF43A047)
val FileTintVideo = Color(0xFFE53935)
val FileTintAudio = Color(0xFFFB8C00)
val FileTintDocument = Color(0xFF1E88E5)
val FileTintPdf = Color(0xFFD32F2F)
val FileTintArchive = Color(0xFF8D6E63)
val FileTintCode = Color(0xFF00897B)
val FileTintApk = Color(0xFF7CB342)
val FileTintOther = Color(0xFF78909C)
